language: cpp
<<<<<<< HEAD

matrix:
  include:
    - os: linux
      compiler:
        - gcc
      dist: trusty
      sudo: required
    - os: linux
      compiler:
        - clang
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.1

# Change this to your needs
script: ./bootstrap.sh && mkdir build && cd build && ../configure && make && ./drachtio --version
=======
compiler:
  - gcc
dist: trusty
sudo: required
>>>>>>> develop

script: 
    - cd  ${TRAVIS_BUILD_DIR}/test
    - rm ./tls/dh1024.pem
    - openssl dhparam -out ./tls/dh1024.pem 1024
    - cat package.json
    - npm install
    - npm test
    - cat /tmp/drachtio.log

git:
    submodules: false

<<<<<<< HEAD
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libcurl4-openssl-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl-config --version; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl-config --libs; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-sed; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gsed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXXFLAGS="-I/usr/local/opt/openssl/include $CXXFLAGS"; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS"; fi
    - git submodule update --init --recursive;
=======
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-7
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    - sudo apt-get install gcc build-essential make git autoconf curl libz-dev ncurses-dev libpcap-dev
    - sudo chmod 0777 /usr/local/src 
    - cd /usr/local/src
    - git clone https://github.com/SIPp/sipp.git && cd sipp && git checkout v3.5.1 
    - ./build.sh  --with-rtpstream --with-pcap 
    - sudo make install
    - sudo apt-get install -y libcurl4-openssl-dev
    - sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
    - sudo apt-get install -y nodejs
    - curl-config --version
    - curl-config --libs 
    - cd $TRAVIS_BUILD_DIR
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - ./bootstrap.sh
    - mkdir build && cd build
    - ../configure
    - make
    - ./drachtio --version 
    - node --version
    - sudo npm install -g npm
>>>>>>> develop
